In [145]:
import pandas as pd 
import numpy as np

In [363]:
df = pd.read_csv("hy_round1_train_20200102/0.csv")

In [364]:
df

,ship,x,y,v,g,time,type,speed_033,speed_6,speed_23,g_90,g_100,g_300
0,0,6.152038e+06,5.124873e+06,2.59,102,1110 11:58:19,拖网,394,10,8,399,10,0
1,0,6.151230e+06,5.125218e+06,2.70,113,1110 11:48:19,拖网,394,10,8,399,10,0
2,0,6.150421e+06,5.125563e+06,2.70,116,1110 11:38:19,拖网,394,10,8,399,10,0
3,0,6.149612e+06,5.125907e+06,3.29,95,1110 11:28:19,拖网,394,10,8,399,10,0
4,0,6.148803e+06,5.126252e+06,3.18,108,1110 11:18:19,拖网,394,10,8,399,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,0,6.118352e+06,5.130672e+06,0.00,0,1107 12:48:30,拖网,394,10,8,399,10,0
410,0,6.118352e+06,5.130672e+06,0.00,0,1107 12:38:32,拖网,394,10,8,399,10,0
411,0,6.118352e+06,5.130672e+06,0.00,0,1107 12:28:32,拖网,394,10,8,399,10,0
412,0,6.118352e+06,5.130672e+06,0.00,0,1107 12:18:30,拖网,394,10,8,399,10,0
413,0,6.118352e+06,5.130672e+06,0.00,0,1107 12:09:28,拖网,394,10,8,399,10,0

In [365]:
def clean(df):
    dt_index = df[df['v'] == 0].index
    dt_index = dt_index.values.tolist()
    data = dt_index.copy()
    for i in range(len(data)-1):        
        data[i] = data[i+1] - data[i]       
    res =[]
    ind=0
    count = 0
    while (ind+count) < len(data)-1 :

        while data[ind + count] == 1:
            count+=1
        if count >3:
            for num in range(count):
                res.append(ind+num)
        ind = ind+count+1
        count = 0
    if b[-1] == (b[-2]+1):
        if (len(b)-2) in res:
            res.append(len(b)-1)
    result =[]
    for i in res:
        result.append(dt_index[i])
    df.drop(result,inplace=True)
    return result

In [366]:
clean(df)

[23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 250,
 251,
 252,
 253,
 254,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413]

In [368]:
df.tail()

,ship,x,y,v,g,time,type,speed_033,speed_6,speed_23,g_90,g_100,g_300
335,0,6.118352e+06,5.130672e+06,0.05,0,1108 01:58:28,拖网,394,10,8,399,10,0
336,0,6.118352e+06,5.130672e+06,0.05,0,1108 01:48:28,拖网,394,10,8,399,10,0
402,0,6.118352e+06,5.130672e+06,0.00,0,1107 14:09:28,拖网,394,10,8,399,10,0
403,0,6.118352e+06,5.130672e+06,0.05,0,1107 13:58:30,拖网,394,10,8,399,10,0
404,0,6.118352e+06,5.130672e+06,0.05,0,1107 13:48:30,拖网,394,10,8,399,10,0

In [362]:
df.drop(a)

,ship,x,y,v,g,time,type,speed_033,speed_6,speed_23,g_90,g_100,g_300
0,0,6.152038e+06,5.124873e+06,2.59,102,1110 11:58:19,拖网,394,10,8,399,10,0
1,0,6.151230e+06,5.125218e+06,2.70,113,1110 11:48:19,拖网,394,10,8,399,10,0
2,0,6.150421e+06,5.125563e+06,2.70,116,1110 11:38:19,拖网,394,10,8,399,10,0
3,0,6.149612e+06,5.125907e+06,3.29,95,1110 11:28:19,拖网,394,10,8,399,10,0
4,0,6.148803e+06,5.126252e+06,3.18,108,1110 11:18:19,拖网,394,10,8,399,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,0,6.118352e+06,5.130672e+06,0.05,0,1108 01:58:28,拖网,394,10,8,399,10,0
336,0,6.118352e+06,5.130672e+06,0.05,0,1108 01:48:28,拖网,394,10,8,399,10,0
402,0,6.118352e+06,5.130672e+06,0.00,0,1107 14:09:28,拖网,394,10,8,399,10,0
403,0,6.118352e+06,5.130672e+06,0.05,0,1107 13:58:30,拖网,394,10,8,399,10,0
404,0,6.118352e+06,5.130672e+06,0.05,0,1107 13:48:30,拖网,394,10,8,399,10,0